# Generated by Django 5.1.6 on 2025-02-27 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='weekday',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='appointments.weekday'),
            preserve_default=False,
        ),
    ]
