# Generated by Django 5.1.6 on 2025-02-27 22:39

from django.db import migrations, models


def set_default_appointment_time(apps, schema_editor):
    Appointment = apps.get_model('appointments', 'Appointment')
    # تعيين الوقت الافتراضي لجميع السجلات التي لا تحتوي على قيمة لحقل appointment_time
    Appointment.objects.filter(appointment_time__isnull=True).update(appointment_time='09:00:00')

class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.RunPython(set_default_appointment_time),
    ]
