# Generated by Django 5.1.6 on 2025-03-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_profile_pic.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='image',
            field=models.ImageField(blank=True, default='specialization_pics/default_specialization_pic.jpg', null=True, upload_to='specialization_pics/'),
        ),
    ]
